# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.27)
{
  # A helpful description of your flake
  description = "ai-production-workshop";

  # Flake inputs
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*";
  };

  # Flake outputs that other flakes can use
  outputs = {
    self,
    flake-schemas,
    nixpkgs,
  }: let
    # Helpers for producing system-specific outputs
    supportedSystems = ["x86_64-linux" "aarch64-linux"];
    forEachSupportedSystem = f:
      nixpkgs.lib.genAttrs supportedSystems (system:
        f {
          pkgs = import nixpkgs {inherit system;};
        });
  in {
    # Schemas tell Nix about the structure of your flake's outputs
    schemas = flake-schemas.schemas;

    # Packages
    packages = forEachSupportedSystem ({pkgs}: let
      webClient = pkgs.buildNpmPackage {
        pname = "ai-production-workshop-web";
        version = "0.1.0";
        src = ./web;
        npmDepsHash = "sha256-hx8VvPI4FLAyklnxZQ0ijXeu0m/rwmz3Bv3qK9uIpsc=";

        installPhase = ''
          runHook preInstall
          mkdir -p $out/app/web/dist
          cp -r dist/* $out/app/web/dist/
          runHook postInstall
        '';
      };

      pythonEnv = pkgs.python314.withPackages (ps:
        with ps; [
          openai
          python-dotenv
          fastapi
          uvicorn
          certifi
        ]);

      appCode = pkgs.stdenv.mkDerivation {
        pname = "ai-production-workshop-app";
        version = "0.1.0";
        src = ./.;
        dontBuild = true;

        installPhase = ''
          runHook preInstall
          mkdir -p $out/app
          cp -r agent server.py cli.py $out/app/
          runHook postInstall
        '';
      };

      dockerImage = pkgs.dockerTools.buildLayeredImage {
        name = "ai-production-workshop";
        tag = "latest";
        contents = [
          pythonEnv
          appCode
          webClient
        ];
        config = {
          Cmd = ["${pythonEnv}/bin/uvicorn" "server:app" "--host" "0.0.0.0" "--port" "8000"];
          WorkingDir = "/app";
          ExposedPorts = {
            "8000/tcp" = {};
          };
        };
      };
    in {
      default = dockerImage;
      inherit webClient pythonEnv appCode;
    });

    # Development environments
    devShells = forEachSupportedSystem ({pkgs}:
      with pkgs; let
        python = python314;
      in {
        default = mkShell {
          # Pinned packages available in the environment
          packages = [
            python
            kompose
            jq
          ];

          # Environment variables
          env = {
            UV_PYTHON = python.interpreter;
            UV_PYTHON_DOWNLOADS = "never";
          };

          # A hook run every time you enter the environment
          shellHook = ''
            unset PYTHONPATH
            export PYTHON_INTERPRETER=${python.interpreter}
            export REPO_ROOT=$(git rev-parse --show-toplevel)
            uv sync
          '';
        };
      });
  };
}
