# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.27)
{
  # A helpful description of your flake
  description = "ai-production-workshop";

  # Flake inputs
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*";
  };

  # Flake outputs that other flakes can use
  outputs = {
    self,
    flake-schemas,
    nixpkgs,
  }: let
    # Helpers for producing system-specific outputs
    supportedSystems = ["x86_64-linux" "aarch64-linux"];
    forEachSupportedSystem = f:
      nixpkgs.lib.genAttrs supportedSystems (system:
        f {
          pkgs = import nixpkgs {inherit system;};
        });
  in {
    # Schemas tell Nix about the structure of your flake's outputs
    schemas = flake-schemas.schemas;

    # Development environments
    devShells = forEachSupportedSystem ({pkgs}:
      with pkgs; let
        python = python314;
      in {
        default = mkShell {
          # Pinned packages available in the environment
          packages = [
            python
            jq
          ];

          # Environment variables
          env = {
            UV_PYTHON = python.interpreter;
            UV_PYTHON_DOWNLOADS = "never";
          };

          # A hook run every time you enter the environment
          shellHook = ''
            unset PYTHONPATH
            export PYTHON_INTERPRETER=${python.interpreter}
            export REPO_ROOT=$(git rev-parse --show-toplevel)
            uv sync
          '';
        };
      });
  };
}
